name: RUNtest
on: [push]

jobs: # jobsは並列実行
    test:
        # OS
        runs-on: ubuntu-latest
        steps: # stepsは上から順番に実行
            - name: echo
              run: |
                  echo "hello"
            - name: echo2
              run: |
                  echo "echo2"
                  echo "echo3"
        
    test2:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: |
                  echo "test2 echo"

    pythontest:
        runs-on: ubuntu-latest

        steps:
            # リポジトリをチェックアウトする
            - name: Checkout
              uses: actions/checkout@v3 # 公式でサポートされている機能
              
            - name: Setup Python 3.7
              uses: actions/setup-python@v2
              with:
                python-version: 3.7
            
            - name: Install pytest
              run: |
                python -m pip install --upgrade pip
                pip install pytest

            # pytest -> JUnit xml形式で結果を出力
            - name: PyTest
              run: |
                python -m pytest test --junit-xml results/pytest.xml

