name: RUNtest
on: [push]

jobs: # jobsは並列実行
    test:
        # OS
        runs-on: ubuntu-latest
        steps: # stepsは上から順番に実行
            - name: echo
              run: |
                  echo "hello"
            - name: echo2
              run: |
                  echo "echo2"
                  echo "echo3"
        
    test2:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: |
                  echo "test2 echo"

