name: RUNtest
on: [push]

jobs:
    test:
        # OS
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: |
                  echo "hello"
            - name: echo2
              run: |
                  echo "echo2"
                  echo "echo3"

