name: pullRequest

on: pull_request

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Print Hello World
            env:
                PRINT: HELLO-WORLD!
            run: |
              echo $PRINT

